blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

blogSpaUserBundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: BlogSpaUserBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

blog_spa_user:
    resource: "@BlogSpaUserBundle/Resources/config/routing.yml"
    prefix:   /

blog_spa_general:
    resource: "@BlogSpaGeneralBundle/Resources/config/routing.yml"
    prefix:   /

# blog_spa_ login:
#     path:     /login
#     defaults: { _controller: AECSBlogBundle:Blog:login }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# app/config/routing.yml
# fos_user:
#     resource: "@FOSUserBundle/Resources/config/routing/all.xml"