blog_spa_user_homepage:
    path:     /
    defaults: { _controller: BlogSpaUserBundle:Default:index }
BloggerBlogBundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: BlogSpaUserBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
